// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'dart:convert' show jsonDecode;
import 'package:flutter/services.dart' show rootBundle;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static String? webApiKeyOverride;
  static String? androidApiKeyOverride;
  static String? iosApiKeyOverride;

  static Future<void> loadSecrets() async {
    if (const bool.fromEnvironment('FLUTTER_TEST')) return;
    try {
      final String response = await rootBundle.loadString('secrets.json');
      final Map<String, dynamic> secrets = jsonDecode(response) as Map<String, dynamic>;
      webApiKeyOverride = secrets['FIREBASE_API_KEY_WEB'] as String?;
      androidApiKeyOverride = secrets['FIREBASE_API_KEY_ANDROID'] as String?;
      iosApiKeyOverride = secrets['FIREBASE_API_KEY_IOS'] as String?;
    } catch (e) {
      print('FAILED TO DYNAMICALLY LOAD SECRETS: $e');
    }
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      final apiKey = webApiKeyOverride ?? web.apiKey;
      _checkKeys('web', apiKey);
      if (webApiKeyOverride != null) {
        return FirebaseOptions(
          apiKey: webApiKeyOverride!,
          appId: web.appId,
          messagingSenderId: web.messagingSenderId,
          projectId: web.projectId,
          authDomain: web.authDomain,
          storageBucket: web.storageBucket,
          measurementId: web.measurementId,
        );
      }
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        final apiKey = androidApiKeyOverride ?? android.apiKey;
        _checkKeys('android', apiKey);
        if (androidApiKeyOverride != null) {
          return FirebaseOptions(
            apiKey: androidApiKeyOverride!,
            appId: android.appId,
            messagingSenderId: android.messagingSenderId,
            projectId: android.projectId,
            storageBucket: android.storageBucket,
          );
        }
        return android;
      case TargetPlatform.iOS:
        final apiKey = iosApiKeyOverride ?? ios.apiKey;
        _checkKeys('ios', apiKey);
        if (iosApiKeyOverride != null) {
          return FirebaseOptions(
            apiKey: iosApiKeyOverride!,
            appId: ios.appId,
            messagingSenderId: ios.messagingSenderId,
            projectId: ios.projectId,
            storageBucket: ios.storageBucket,
            androidClientId: ios.androidClientId,
            iosClientId: ios.iosClientId,
            iosBundleId: ios.iosBundleId,
          );
        }
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static void _checkKeys(String platform, String apiKey) {
    if (apiKey.isEmpty && !const bool.fromEnvironment('FLUTTER_TEST')) {
      throw UnsupportedError(
        'Firebase API Key for $platform is not configured. '
        'Please create a secrets.json file in the root of the project with '
        'your keys and run the app with --dart-define-from-file=secrets.json.',
      );
    }
  }


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_ANDROID'),
    appId: '1:933796135635:android:efa8a5f64b2a9271680a26',
    messagingSenderId: '933796135635',
    projectId: 'timeflip-e3747',
    storageBucket: 'timeflip-e3747.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WEB'),
    appId: '1:933796135635:web:8d2c71e0b703b142680a26',
    messagingSenderId: '933796135635',
    projectId: 'timeflip-e3747',
    authDomain: 'timeflip-e3747.firebaseapp.com',
    storageBucket: 'timeflip-e3747.firebasestorage.app',
    measurementId: 'G-4Z8H57LB60',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_IOS'),
    appId: '1:933796135635:ios:f0d20a894cab0521680a26',
    messagingSenderId: '933796135635',
    projectId: 'timeflip-e3747',
    storageBucket: 'timeflip-e3747.firebasestorage.app',
    androidClientId: '933796135635-mmva97nrqffng2f259gn4maaovagbb7h.apps.googleusercontent.com',
    iosClientId: '933796135635-ppi5gcnd38v578e7ah1rfl5rc4hue6pa.apps.googleusercontent.com',
    iosBundleId: 'com.focusflip.focusflip',
  );
}
