// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIdP6TIcCKFP-sVnuhDPEb6_eDycfdesA',
    appId: '1:933796135635:android:efa8a5f64b2a9271680a26',
    messagingSenderId: '933796135635',
    projectId: 'timeflip-e3747',
    storageBucket: 'timeflip-e3747.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ3LPLJjZ2kRrbbkysRHoNNzPpqEBm4QI',
    appId: '1:933796135635:web:8d2c71e0b703b142680a26',
    messagingSenderId: '933796135635',
    projectId: 'timeflip-e3747',
    authDomain: 'timeflip-e3747.firebaseapp.com',
    storageBucket: 'timeflip-e3747.firebasestorage.app',
    measurementId: 'G-4Z8H57LB60',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn0eR2VUSW8viHk2UeZza12InpppfNWIs',
    appId: '1:933796135635:ios:f0d20a894cab0521680a26',
    messagingSenderId: '933796135635',
    projectId: 'timeflip-e3747',
    storageBucket: 'timeflip-e3747.firebasestorage.app',
    androidClientId: '933796135635-mmva97nrqffng2f259gn4maaovagbb7h.apps.googleusercontent.com',
    iosClientId: '933796135635-ppi5gcnd38v578e7ah1rfl5rc4hue6pa.apps.googleusercontent.com',
    iosBundleId: 'com.focusflip.focusflip',
  );
}
